### PR TITLE
Allow dynamic connection name

### PR DESCRIPTION
**Pull request by yakatz**
This PR changes the way a connection name is selected for a Model. Previously the value was loaded from a property `$this->connection`, but that value had to be set statically. Inspired by Laravel auth redirect handling, this change makes the model check for a method named `connection()`  which will supply a connection name and falls back on the previous `connection` property.

This is a potential solution to https://github.com/DirectoryTree/LdapRecord-Laravel/discussions/348

----

Example Usage:

On your model, create a function that returns the name of the LDAP connection to use. For my example, I want to bind as the current user (see https://github.com/DirectoryTree/LdapRecord-Laravel/discussions/348)
I created this as a trait for easy reuse:
```php
<?php

namespace App\Ldap\Traits;

use Illuminate\Support\Facades\Auth;

trait RunAsUser
{
    public function connection()
    {
        $connection = 'ldap';

        if ( (! app()->runningInConsole()) && ($user = Auth::user()) ) {
            return strtr(':baseconnection-:username', [
                ':baseconnection' => $connection,
                ':username' => $user->getUsername(),
            ]);
        }

        return $connection;
    }
}
```

Since I am running in Laravel, I also create this middleware to make sure the needed LDAP connection exists:
```php
<?php 

namespace App\Http\Middleware;

use App\Ldap\Traits\RunAsUser;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Crypt;
use LdapRecord\Connection;
use LdapRecord\Container;

class LdapRunAs
{
    use RunAsUser;

    public function handle($request, Closure $next)
    {
        if (
            Auth::user() &&
            session()->has('ldap_user.username') &&
            session()->has('ldap_user.password') && 
            ! Container::exists($this->connection()))
        {
            $config = config(strtr('ldap.connections.:baseconnection', [
                ':baseconnection' => $this->getBaseLdapConnection(),
            ]));

            $config['username'] = session()->get('ldap_user.username');
            $config['password'] = Crypt::decryptString(session()->get('ldap_user.password'));

            $ldap_connection = $this->makeLdapConnection($config);
            Container::addConnection($ldap_connection, $this->connection());
        }

        return $next($request);
    }

    protected function makeLdapConnection($config)
    {
        return app(Connection::class, ['config' => $config]);
    }
}
```

In the Model, it is now as simple as adding:
```php
<?php

namespace App\Ldap\Mail;

use App\Ldap\Traits\RunAsUser;
use LdapRecord\Models\___\Entry as Model;

class Alias extends Model
{
    use RunAsUser;
}

```

### CODE REVIEW

**Comment by stevebauman** [comment]
Hi @yakatz, thanks for the PR!

Couldn't you simply add this functionality on your custom LDAP models? This seems very application specific, so I'm not sure if this would be of significant benefit to be added into the core for other developers (unless I'm misunderstanding).

**Comment by yakatz** [comment]
I probably put too much distractive descriptive text in the PR description. My use case can't be added to custom code without the PR - the PR allows calling a method instead of loading the value from a property.
This is inspired by Laravel's redirect handling: https://github.com/laravel/ui/blob/3.x/auth-backend/RedirectsUsers.php - if a method exists, call it, otherwise load the value from the property.

**Comment by stevebauman** [comment]
Apologies for the late reply @yakatz.

> the PR allows calling a method instead of loading the value from a property.

Right, but can't you override the `getConnectionName()` method with your own method and not use the property? Ex:

```php
public function getConnectionName()
{
    // Resolve connection name your own way...

    // Or return the default via property...
    return parent::getConnectionName();
}
```

**Comment by yakatz** [comment]
You're right, I was so focused on how other packages do it that I didn't think of that.

**Pull request closed without merging**
