### PR TITLE
Add ability to override model matching using relation static callback

### PR DESCRIPTION
**Pull request by stevebauman**
Closes #443

@yakatz will this work for you?

```php
use LdapRecord\Models\Relations\Relation;

Relation::setModelResolver(function ($modelObjectClasses, $relationMap, Model $model) {
    // Determine and return model class using custom matching algo...
});
```

### CODE REVIEW

**Comment by yakatz** [comment]
I can give it a try. Where would you put this call (using Laravel if it matters)?

**Comment by stevebauman** [comment]
I would personally put it in your `AppServiceProvider` in the `register()/boot()` method 👍 

I believe you should be able to place your custom matching code right into the callback (you may need to `uasort()` the related classes):

```php
Relation::setModelResolver(function ($modelClasses, $relatedClasses) {
    uasort($relatedClasses, fn (array $a, array $b) => count($a) <=> count($b));

    // Check if each relationship is a subset of the classes of the retreived entry
    foreach ($relatedClasses as $modelName => $modelClasses) {
        $classIntersection = array_values(array_intersect($entryClasses, $modelClasses));

        if ($classIntersection == $modelClasses) {
            return $modelName;
        }
    }
});
```

**Comment by stevebauman** [comment]
Any update by chance @yakatz? Wondering if I should merge this in 👍

**Comment by yakatz** [comment]
I finally got a chance to try this. It works as expected. I think the variable names are a bit confusing (and the sample code in this PR doesn't work because of repeated variable names).

```php
Relation::resolveModelsUsing(function ($modelInstanceClasses, $relatedClasses, $model) {
    // Sort related models by number of classes (largest to smallest)
    uasort($relatedClasses, fn (array $a, array $b) => count($a) <=> count($b));

    // Check if each relationship is a subset of the classes of the retrieved entry
    foreach ($relatedClasses as $modelName => $modelClasses) {
        $classIntersection = array_values(array_intersect($modelInstanceClasses, $modelClasses));

        if ($classIntersection == $modelClasses) {
            return $modelName;
        }
    }
});
```

**Pull request merged**
