### PR TITLE
Don't use return on void functions

### PR DESCRIPTION
**Pull request by NicolasCARPi**
Also, is there a reason why you're not using return typing? I mean have `function blah(): void` instead of `@return void` in the docblock.

### CODE REVIEW

**Comment by stevebauman** [comment]
Hi @NicolasCARPi!

> Also, is there a reason why you're not using return typing?

I don't want to enforce return types. 👍  

In my view -- you either have return types or doc-blocks, but not both. Laravel adopts this.

> Don't use return on void functions

I closely follow and adopt the Laravel code-style, which uses early returns (even on `void` functions/methods). This is another personal preference.

I appreciate the PR, though this conflicts with the code style from around the repository. Hope that's understandable! ❤️

**Comment by NicolasCARPi** [comment]
Sure no problem! I'm more of a Symfony guy myself ;p

Note that this was flagged by phpstan:

2021-04-01-153733_619x108_scrot

**Comment by stevebauman** [comment]
Haha makes sense! My preferences tend to change over time so it's possible I may revisit this style in the future and adopt it. 👍

**Comment by stevebauman** [comment]
Speaking of Symfony -- would you have use for an LdapRecord symfony bundle? Have been thinking of building one, though my experience with Symfony is basically zero.

**Comment by NicolasCARPi** [comment]
Honestly no. The great thing with symfony is that you can use it outside of the complete framework. So my app doesn't use symfony in full but only what I need from symfony (httpfoundation, console, process, filesystem, ...). That means no bundle and no symfony automagic configuration with yaml files. So I don't think you need to spend time on that. It's fine like that.

~Nico

**Comment by stevebauman** [comment]
Ah okay understood. Thanks for your input and response! Really appreciate it.

**Pull request closed without merging**
