### PR TITLE
[Feature] `Paginator::forPage()` for slicing paginated search results

### PR DESCRIPTION
**Pull request by janickiy**
added a new method for the pagination of search results

### CODE REVIEW

**Comment by stevebauman** [comment]
Hi there, thanks for the PR @janickiy.

Could you explain what this new paginate feature is for?

**Comment by janickiy** [comment]
> Hi there, thanks for the PR @janickiy.
> 
> Could you explain what this new paginate feature is for?

Hi Steve! I need a method where I could set 2 parameters: limit and offset. In paginate I can set only limit.

**Comment by janickiy** [comment]
> Hi there, thanks for the PR @janickiy.
> 
> Could you explain what this new paginate feature is for?

Hi Steve! I need a method where I could set 2 parameters: limit and offset. In paginate I can set only limit.

**Comment by stevebauman** [comment]
Closing this as you can achieve this using the `chunk()` method:

```php
$users = null;
$currentPage = 1;

User::chunk(1000, function ($results, $page) use (&$users, $currentPage) {
    if ($page === $currentPage) {
        $users = $results;
        
        // Break the chunk.
        return false;
    }
});
```

Thank you for your time on the PR 🙏

**Comment by janickiy** [comment]
> Closing this as you can achieve this using the `chunk()` method:
> 
> ```
> $users = null;
> $currentPage = 1;
> 
> User::chunk(1000, function ($results, $page) use (&$users, $currentPage) {
>     if ($page === $currentPage) {
>         $users = $results;
>         
>         // Break the while loop.
>         return false;
>     }
> });
> ```
> 
> Thank you for your time on this PR 🙏

Sorry, I can't use User::chunk.  My base_dn has  a dynamic value. Via $connection
            ->query() chunck does not work.

**Comment by stevebauman** [comment]
> Sorry, I can't use User::chunk. My base_dn has a dynamic value.

You can use the `in()` method to set your base DN to whatever you'd like on LdapRecord models:

```php
use LdapRecord\Models\Entry;

Entry::in($baseDn)->chunk(...);
```

Does this resolve your issue?

**Pull request closed without merging**
